### ISSUE TITLE
Срок регистрации домена golang-book.ru истёк 

### ISSUE THREAD

**Issue by wkepting** [zenwalker/golang-book#80]
При заходе на сайт вылазит страница от рег ру с информацией о том, что требуется продление домена

Будет очень неприятно, если сайт с столь полезным переводом выкупят люди с недобросовестными намерениями

![image](https://user-images.githubusercontent.com/60810530/202846605-3f7821eb-04ed-42de-8396-12ec3775c1ce.png)

**Comment by mavriq** [comment]
ребят, купите обратно скорее домен

а то у меня уже чешутся руки купить его, и повесить заглушку "зачем вам эта гошка? учите лучше python"

а если серьезно - присоединяюсь к просьбе пофиксить такую глупую проблему
... и повесить мониторинг

**Comment by zlocate** [comment]
Готов приобрести его для нужн комьюнити как только освободится. 
Это произойдет через месяц только.
Если будет занят форкну репо и выложу на другом домене и скину вам его в issue

**Comment by wkepting** [comment]
Ну, сам по себе перевод есть в читаемом виде прямо в этом репозитории
Просто домен жалко. Я бы сам его купил для комьюнити, но кажись либо цена будет непосильной, либо в свободный доступ он даже не попадёт, сразу уйдёт на аукцион или куда-нибудь

**Comment by wkepting** [comment]
Сайт прекрасно работает. Либо авторы спохватились, либо кто-то выкупил домен. Спасибо тому, кто вернул перевод на сайт. Во всяком случае, дело можно считать закрытым.
